"""add_post_type_to_blog_posts

Revision ID: 0df00e14983a
Revises: f9e55edaa5ee
Create Date: 2025-11-27 09:45:00.716416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0df00e14983a'
down_revision = 'f9e55edaa5ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_subscriptions_email'), 'email_subscriptions', ['email'], unique=True)
    op.create_index(op.f('ix_email_subscriptions_id'), 'email_subscriptions', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_id', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_email_code', 'password_reset_tokens', ['email', 'code'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_code'), 'password_reset_tokens', ['code'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('post_id', sa.String(length=255), nullable=False),
    sa.Column('reporter_id', sa.String(length=255), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_post_id'), 'reports', ['post_id'], unique=False)
    # Add post_type column with default 'blog' for existing records
    op.add_column('blog_posts', sa.Column('post_type', sa.String(length=20), nullable=False, server_default='blog'))
    op.create_index(op.f('ix_blog_posts_post_type'), 'blog_posts', ['post_type'], unique=False)
    op.add_column('event_registrations', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('event_registrations', sa.Column('rejection_reasons', sa.JSON(), nullable=True))
    op.add_column('event_registrations', sa.Column('rejection_description', sa.Text(), nullable=True))
    op.add_column('event_registrations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('account_number', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('account_holder_name', sa.String(length=255), nullable=True))
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               type_=sa.String(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               existing_nullable=True)
    op.drop_column('events', 'account_holder_name')
    op.drop_column('events', 'account_number')
    op.drop_column('events', 'bank_name')
    op.drop_column('event_registrations', 'updated_at')
    op.drop_column('event_registrations', 'rejection_description')
    op.drop_column('event_registrations', 'rejection_reasons')
    op.drop_column('event_registrations', 'status')
    op.drop_index(op.f('ix_blog_posts_post_type'), table_name='blog_posts')
    op.drop_column('blog_posts', 'post_type')
    op.drop_index(op.f('ix_reports_post_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_code'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_email_code', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_email_subscriptions_id'), table_name='email_subscriptions')
    op.drop_index(op.f('ix_email_subscriptions_email'), table_name='email_subscriptions')
    op.drop_table('email_subscriptions')
    # ### end Alembic commands ###

