"""Add avatar to user

Revision ID: 59087632c4d9
Revises: 3ee43241167f
Create Date: 2025-11-22 23:06:05.904208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59087632c4d9'
down_revision = '3ee43241167f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###

