"""add_status_to_blog_post

Revision ID: 9e2725d601e6
Revises: 59087632c4d9
Create Date: 2025-11-23 00:40:26.544881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2725d601e6'
down_revision = '59087632c4d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'status')
    # ### end Alembic commands ###

