"""add_role_to_user_and_status_to_event

Revision ID: f9e55edaa5ee
Revises: 9e2725d601e6
Create Date: 2025-11-23 00:49:48.927020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e55edaa5ee'
down_revision = '9e2725d601e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('events', 'status')
    # ### end Alembic commands ###

